### ISSUE TITLE
USGDT013 - Admin - Cycle de vie des véhicules

### ISSUE THREAD

**Issue by ghdiginamic** [2019-d05-code/gestion-des-transports-front#13]
En tant qu'administrateur, je souhaite pouvoir gérer le cycle de vie d'un véhicule de société.

# Critères d'acceptation

![](https://github.com/DiginamicFormation/ressources-atelier/raw/master/gestion-du-transport/admin.vehicules.details.cyclevie.png)

* [x] Le statut du véhicule est désormais visible de la page de détails d'un véhicule. Les statuts possibles :
    * EN SERVICE
    * EN REPARATION
    * HORS SERVICE
* [x] Le bouton _Mettre en réparation_ n'est accessible que si le véhicule est au statut _EN SERVICE_ ou _HORS SERVICE_.
* [x] Le bouton _Mettre en service_ n'est accessible que si le véhicule est au statut _HORS SERVICE_ ou _EN REPARATION_.
* [x] Le bouton _Hors service_ n'est accessible que si le véhicule est au statut _EN SERVICE_ ou _EN REPARATION_.
* [x] Le bouton _Mettre en réparation_ permet de passer le véhicule au statut _EN REPARATION_.
* [x] Le bouton _Mettre en service_ permet de passer le véhicule au statut _EN SERVICE_.
* [x] Le bouton _Hors service_ permet de passer le véhicule au statut _HORS SERVICE_.
* [x] Seuls les véhicules ayant le statut _EN SERVICE_ peuvent être réservés.

**Comment by ElenHayot** [comment]
Annulation de réservation ==> nouvelle issue?
Point en suspens
